# Generated by Django 4.0.6 on 2022-07-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_src', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('bio', models.CharField(max_length=250)),
                ('avatar_src', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarksModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('is_bookmark', models.BooleanField(default=False)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('likes', models.IntegerField(default=0)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('tags', models.CharField(max_length=50)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(verbose_name='date published')),
                ('content', models.ManyToManyField(to='main.mediamodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='media_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mediatypemodel'),
        ),
        migrations.CreateModel(
            name='FollowerFollowingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ManyToManyField(related_name='follower', to='main.usermodel')),
                ('following_id', models.ManyToManyField(related_name='following', to='main.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='basemodel',
            name='post_id',
            field=models.ManyToManyField(to='main.postmodel'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='user_id',
            field=models.ManyToManyField(to='main.usermodel'),
        ),
    ]
