# Generated by Django 4.0.6 on 2022-07-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_src', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('bio', models.CharField(max_length=250)),
                ('avatar_src', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('is_bookmark', models.BooleanField(default=False)),
            ],
            bases=('main.base',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('likes', models.IntegerField(default=0)),
            ],
            bases=('main.base',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.base')),
                ('tags', models.CharField(max_length=50)),
            ],
            bases=('main.base',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(verbose_name='date published')),
                ('content', models.ManyToManyField(to='main.media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='media_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mediatype'),
        ),
        migrations.AddField(
            model_name='base',
            name='post_id',
            field=models.ManyToManyField(to='main.post'),
        ),
        migrations.AddField(
            model_name='base',
            name='user_id',
            field=models.ManyToManyField(to='main.user'),
        ),
    ]
