# Generated by Django 4.1 on 2022-09-19 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mediamodel_media_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar_src',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbwofa3rl/image/upload/v1663590111/avatars/avatar_ox54lh.png', max_length=255),
        ),
    ]
